import type { InsertActivity } from "@workspace/db";

export const CORE_ACTIVITIES: InsertActivity[] = [
  // ── Fitness ──
  { name: "gym", displayName: "Gym Workout", description: "Gym workout (1 hour)", category: "fitness",
    xpRewards: [{ statName: "strength", amount: 40 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 1 },
  { name: "running", displayName: "Running", description: "Running / Cardio (20 min)", category: "fitness",
    xpRewards: [{ statName: "stamina", amount: 30 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 2 },
  { name: "basketball", displayName: "Basketball", description: "Basketball game or practice", category: "fitness",
    xpRewards: [{ statName: "athletics", amount: 40 }, { statName: "stamina", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 3 },
  { name: "soccer", displayName: "Soccer", description: "Soccer game or practice", category: "fitness",
    xpRewards: [{ statName: "athletics", amount: 40 }, { statName: "stamina", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 4 },
  { name: "swimming", displayName: "Swimming", description: "Swimming laps or session", category: "fitness",
    xpRewards: [{ statName: "stamina", amount: 35 }, { statName: "health", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 5 },
  { name: "cycling", displayName: "Cycling", description: "Bike ride or indoor cycling", category: "fitness",
    xpRewards: [{ statName: "stamina", amount: 30 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 6 },
  { name: "martialArts", displayName: "Martial Arts", description: "Boxing, BJJ, MMA, etc.", category: "fitness",
    xpRewards: [{ statName: "strength", amount: 30 }, { statName: "discipline", amount: 20 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 7 },
  { name: "yoga", displayName: "Yoga", description: "Yoga session", category: "fitness",
    xpRewards: [{ statName: "health", amount: 25 }, { statName: "discipline", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 8 },
  { name: "hiking", displayName: "Hiking", description: "Trail hike or nature walk", category: "fitness",
    xpRewards: [{ statName: "stamina", amount: 25 }, { statName: "health", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 9 },

  // ── Intellectual ──
  { name: "study", displayName: "Study / Learning", description: "Studying or learning (1 hour)", category: "intellect",
    xpRewards: [{ statName: "intellect", amount: 35 }, { statName: "discipline", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 10 },
  { name: "deepWork", displayName: "Deep Work Block", description: "Deep focus work (1 hour)", category: "intellect",
    xpRewards: [{ statName: "discipline", amount: 40 }, { statName: "intellect", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 11 },
  { name: "reading", displayName: "Reading", description: "Reading books or articles", category: "intellect",
    xpRewards: [{ statName: "intellect", amount: 25 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 12 },
  { name: "coding", displayName: "Coding", description: "Programming or building projects", category: "intellect",
    xpRewards: [{ statName: "intellect", amount: 35 }, { statName: "creativity", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 13 },
  { name: "language", displayName: "Language Study", description: "Practicing a new language", category: "intellect",
    xpRewards: [{ statName: "intellect", amount: 30 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 14 },

  // ── Creative ──
  { name: "piano", displayName: "Piano Practice", description: "Piano or keyboard practice", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 40 }, { statName: "discipline", amount: 20 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 20 },
  { name: "guitar", displayName: "Guitar Practice", description: "Guitar or bass practice", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 40 }, { statName: "discipline", amount: 20 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 21 },
  { name: "singing", displayName: "Singing", description: "Vocal practice or singing", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 30 }, { statName: "charisma", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 22 },
  { name: "drawing", displayName: "Drawing / Art", description: "Drawing, painting, or digital art", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 40 }, { statName: "discipline", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 23 },
  { name: "writing", displayName: "Creative Writing", description: "Journaling, stories, poetry", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 30 }, { statName: "intellect", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 24 },
  { name: "photography", displayName: "Photography", description: "Photo shooting or editing", category: "creativity",
    xpRewards: [{ statName: "creativity", amount: 30 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 25 },

  // ── Discipline ──
  { name: "coldShower", displayName: "Cold Shower", description: "Cold shower (2-3 min)", category: "discipline",
    xpRewards: [{ statName: "discipline", amount: 15 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 30 },
  { name: "meditation", displayName: "Meditation", description: "Mindfulness or meditation", category: "discipline",
    xpRewards: [{ statName: "discipline", amount: 20 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 31 },
  { name: "plannedDay", displayName: "Planned Day", description: "Planned the day in advance", category: "discipline",
    xpRewards: [{ statName: "discipline", amount: 20 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 32 },
  { name: "noSocialMedia", displayName: "No Social Media", description: "Full day without social media", category: "discipline",
    xpRewards: [{ statName: "discipline", amount: 25 }, { statName: "health", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 33 },
  { name: "earlyWakeup", displayName: "Early Wakeup", description: "Woke up before 7 AM", category: "discipline",
    xpRewards: [{ statName: "discipline", amount: 20 }, { statName: "health", amount: 5 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 34 },

  // ── Social ──
  { name: "socialized", displayName: "Socialized", description: "Meaningful social interaction", category: "social",
    xpRewards: [{ statName: "charisma", amount: 25 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 40 },
  { name: "networking", displayName: "Networking", description: "Professional networking", category: "social",
    xpRewards: [{ statName: "charisma", amount: 20 }, { statName: "intellect", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 41 },
  { name: "volunteering", displayName: "Volunteering", description: "Community service or volunteering", category: "social",
    xpRewards: [{ statName: "charisma", amount: 25 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 42 },

  // ── Health ──
  { name: "drankWater", displayName: "Drank 3L Water", description: "Stayed hydrated (3L+)", category: "health",
    xpRewards: [{ statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 50 },
  { name: "healthyMeal", displayName: "Healthy Meal Prep", description: "Cooked a healthy meal", category: "health",
    xpRewards: [{ statName: "health", amount: 15 }, { statName: "discipline", amount: 5 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 51 },
  { name: "stretching", displayName: "Stretching", description: "Full stretching routine", category: "health",
    xpRewards: [{ statName: "health", amount: 15 }, { statName: "stamina", amount: 5 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 52 },

  // ── Wealth & Career ──
  { name: "work", displayName: "Work / Job", description: "Hours at work or productive job time", category: "intellect",
    xpRewards: [{ statName: "wealth", amount: 40 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 60 },
  { name: "freelance", displayName: "Freelance / Side Hustle", description: "Freelance work or side business", category: "intellect",
    xpRewards: [{ statName: "wealth", amount: 35 }, { statName: "creativity", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 61 },
  { name: "careerStudy", displayName: "Career Study", description: "Studying for career advancement", category: "intellect",
    xpRewards: [{ statName: "wealth", amount: 30 }, { statName: "intellect", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 62 },
  { name: "budgeting", displayName: "Budgeting / Expense Tracking", description: "Tracked expenses or managed budget", category: "discipline",
    xpRewards: [{ statName: "wealth", amount: 20 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 63 },
  { name: "investing", displayName: "Investing / Finance Learning", description: "Researched investing or managed portfolio", category: "intellect",
    xpRewards: [{ statName: "wealth", amount: 25 }, { statName: "intellect", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 64 },
  { name: "projectWork", displayName: "Build a Project", description: "Worked on a personal or portfolio project", category: "intellect",
    xpRewards: [{ statName: "wealth", amount: 30 }, { statName: "creativity", amount: 15 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 65 },
  { name: "jobApplication", displayName: "Job Application", description: "Applied to a job or updated resume", category: "discipline",
    xpRewards: [{ statName: "wealth", amount: 25 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 66 },

  // ── Family ──
  { name: "familyTime", displayName: "Family Time", description: "Quality time spent with family", category: "family",
    xpRewards: [{ statName: "family", amount: 30 }, { statName: "health", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 70 },
  { name: "familyCall", displayName: "Called Family", description: "Called a parent, sibling, or relative", category: "family",
    xpRewards: [{ statName: "family", amount: 20 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 71 },
  { name: "familyMeal", displayName: "Family Meal", description: "Shared a meal with family", category: "family",
    xpRewards: [{ statName: "family", amount: 25 }, { statName: "health", amount: 5 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 72 },
  { name: "familyHelp", displayName: "Helped Family", description: "Helped a family member with something", category: "family",
    xpRewards: [{ statName: "family", amount: 25 }, { statName: "discipline", amount: 10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 73 },

  // ── Bad habits (penalties) ──
  { name: "junkFood", displayName: "Ate Junk Food", description: "Ate junk food (penalty)", category: "bad_habit",
    xpRewards: [{ statName: "health", amount: -20 }, { statName: "discipline", amount: -10 }],
    isCore: true, isReusable: true, archived: false, sortOrder: 90 },
];
