import type { InsertActivity } from "@workspace/db";

export const CORE_ACTIVITIES: InsertActivity[] = [
  {
    name: "gym",
    displayName: "Gym Workout",
    description: "Gym workout (1 hour)",
    category: "fitness",
    xpRewards: [
      { statName: "strength", amount: 40 },
      { statName: "discipline", amount: 10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 1,
  },
  {
    name: "running",
    displayName: "Running",
    description: "Running / Cardio (20 min)",
    category: "fitness",
    xpRewards: [
      { statName: "stamina", amount: 30 },
      { statName: "health", amount: 10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 2,
  },
  {
    name: "basketball",
    displayName: "Basketball",
    description: "Basketball (1 hour)",
    category: "athletics",
    xpRewards: [
      { statName: "athletics", amount: 50 },
      { statName: "stamina", amount: 20 },
      { statName: "health", amount: -10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 3,
  },
  {
    name: "study",
    displayName: "Study / Learning",
    description: "Studying (1 hour)",
    category: "intellect",
    xpRewards: [
      { statName: "intellect", amount: 35 },
      { statName: "focus", amount: 15 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 10,
  },
  {
    name: "deepWork",
    displayName: "Deep Work Block",
    description: "Deep focus work (1 hour)",
    category: "focus",
    xpRewards: [
      { statName: "focus", amount: 40 },
      { statName: "discipline", amount: 15 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 11,
  },
  {
    name: "piano",
    displayName: "Piano Practice",
    description: "Piano practice (1 hour)",
    category: "creativity",
    xpRewards: [
      { statName: "creativity", amount: 40 },
      { statName: "focus", amount: 20 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 20,
  },
  {
    name: "socialized",
    displayName: "Socialized",
    description: "Talked to new person",
    category: "social",
    xpRewards: [
      { statName: "charisma", amount: 25 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 21,
  },
  {
    name: "coldShower",
    displayName: "Cold Shower",
    description: "Cold shower (2-3 min)",
    category: "discipline",
    xpRewards: [
      { statName: "discipline", amount: 15 },
      { statName: "health", amount: 10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 30,
  },
  {
    name: "meditation",
    displayName: "Meditated",
    description: "Meditation session",
    category: "focus",
    xpRewards: [
      { statName: "focus", amount: 20 },
      { statName: "health", amount: 10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 31,
  },
  {
    name: "plannedDay",
    displayName: "Planned Day",
    description: "Planned the day",
    category: "discipline",
    xpRewards: [
      { statName: "discipline", amount: 20 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 32,
  },
  {
    name: "drankWater",
    displayName: "Drank 3L Water",
    description: "Stayed hydrated (3L+)",
    category: "health",
    xpRewards: [
      { statName: "health", amount: 10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 33,
  },
  {
    name: "junkFood",
    displayName: "Ate Junk Food",
    description: "Ate junk food (penalty)",
    category: "bad_habit",
    xpRewards: [
      { statName: "health", amount: -20 },
      { statName: "discipline", amount: -10 },
    ],
    isCore: true,
    isReusable: true,
    archived: false,
    sortOrder: 90,
  },
];
